all: Bipartite LongestCommon
	@true

Bipartite: Bipartite.cpp
	g++ -std=c++0x -pedantic -o Bipartite Bipartite.cpp -Wall -Werror

LongestCommon: LongestCommon.cpp
	g++ -std=c++0x -pedantic -o LongestCommon LongestCommon.cpp -Wall -Werror
